#include "Engine/app_hooks.h"
#include "Engine/text.h"
#include "game_internal.h"
#include <string.h>
demo_game_t g_game;
static bool add_texture(const char*p){const texture_t*t=texture_create(p,TEX_FILTER_LINEAR,TEX_WRAP_REPEAT);return t&&t->id&&t!=texture_get_fallback();}
bool bge_app_register_resources(void){if(!add_texture("Game/res/ground.png"))return false;if(!add_texture("Game/res/stone.png"))return false;if(!add_texture("Game/res/awesomeface.png"))return false;const texture_t*solid=texture_create_solid(255,255,255);if(!solid||!solid->id||solid==texture_get_fallback())return false;if(!add_texture("Game/res/metal_a.png"))return false;if(!add_texture("Game/res/metal_b.png"))return false;if(!add_texture("Game/res/grate.png"))return false;if(!add_texture("Game/res/spider.png"))return false;if(!add_texture("Game/res/banana.png"))return false;if(!add_texture("Game/res/water.png"))return false;if(!add_texture("Game/res/gun_doom.png"))return false;if(!add_texture("Game/res/gun_portal.png"))return false;if(!add_texture("Game/res/hand_shoot_flash.png"))return false;if(!add_texture("Game/res/hand_shoot_3.png"))return false;if(!add_texture("Game/res/hand_shoot_4.png"))return false;return add_texture("Game/res/hand_shoot_5.png");}
bool bge_app_init(level_data_t*l){if(!l)return false;memset(&g_game,0,sizeof(g_game));game_player_init(&g_game.player);game_gun_reset(&g_game.gun);g_game.gun.defs[g_game.gun.count++]=(game_weapon_def_t){.tex_names={"Game/res/gun_doom.png"},.tex_count=1,.flash_tex_name="Game/res/hand_shoot_flash.png",.gun_xy={.5f,1},.gun_size=.43f,.flash_size=.12f,.flash_xy={.53f,.44f}};g_game.gun.defs[g_game.gun.count++]=(game_weapon_def_t){.tex_names={"Game/res/gun_portal.png"},.tex_count=1,.flash_tex_name="Game/res/hand_shoot_flash.png",.gun_xy={.78f,1},.gun_size=.33f,.flash_size=.22f,.flash_xy={.32f,.39f}};g_game.gun.defs[g_game.gun.count++]=(game_weapon_def_t){.tex_names={"Game/res/hand_shoot_3.png","Game/res/hand_shoot_4.png","Game/res/hand_shoot_5.png"},.tex_count=3,.flash_tex_name="Game/res/hand_shoot_flash.png",.gun_xy={.67f,1},.gun_size=.52f,.flash_size=.07f,.flash_xy={.32f,.26f},.frame_duration=.04f};return game_gun_init(&g_game.gun);}
void bge_app_shutdown(void){game_gun_shutdown(&g_game.gun);memset(&g_game,0,sizeof(g_game));}
