#include <cbuild.h>
static void add_imgui(C_Target*a){c_sources(a,"Vendor/imgui/imgui.cpp");c_sources(a,"Vendor/imgui/imgui_draw.cpp");c_sources(a,"Vendor/imgui/imgui_tables.cpp");c_sources(a,"Vendor/imgui/imgui_widgets.cpp");c_sources(a,"Vendor/imgui/imgui_impl_glfw.cpp");c_sources(a,"Vendor/imgui/imgui_impl_opengl3.cpp");}
static void add_glfw(C_Target*a){c_sources(a,"Vendor/glfw/src/context.c");c_sources(a,"Vendor/glfw/src/init.c");c_sources(a,"Vendor/glfw/src/input.c");c_sources(a,"Vendor/glfw/src/monitor.c");c_sources(a,"Vendor/glfw/src/platform.c");c_sources(a,"Vendor/glfw/src/vulkan.c");c_sources(a,"Vendor/glfw/src/window.c");c_sources(a,"Vendor/glfw/src/egl_context.c");c_sources(a,"Vendor/glfw/src/osmesa_context.c");c_sources(a,"Vendor/glfw/src/null_init.c");c_sources(a,"Vendor/glfw/src/null_monitor.c");c_sources(a,"Vendor/glfw/src/null_window.c");c_sources(a,"Vendor/glfw/src/null_joystick.c");
#ifdef _WIN32
c_define(a,"_GLFW_WIN32");c_sources(a,"Vendor/glfw/src/win32_init.c");c_sources(a,"Vendor/glfw/src/win32_joystick.c");c_sources(a,"Vendor/glfw/src/win32_module.c");c_sources(a,"Vendor/glfw/src/win32_monitor.c");c_sources(a,"Vendor/glfw/src/win32_thread.c");c_sources(a,"Vendor/glfw/src/win32_time.c");c_sources(a,"Vendor/glfw/src/win32_window.c");c_sources(a,"Vendor/glfw/src/wgl_context.c");
#elif defined(__APPLE__)
c_define(a,"_GLFW_COCOA");c_sources(a,"Vendor/glfw/src/macos_time.c");c_sources(a,"Vendor/glfw/src/posix_module.c");c_sources(a,"Vendor/glfw/src/posix_thread.c");c_sources(a,"Vendor/glfw/src/cocoa_init.m");c_sources(a,"Vendor/glfw/src/cocoa_joystick.m");c_sources(a,"Vendor/glfw/src/cocoa_monitor.m");c_sources(a,"Vendor/glfw/src/cocoa_window.m");c_sources(a,"Vendor/glfw/src/nsgl_context.m");
#else
c_define(a,"_GLFW_X11");c_define(a,"_DEFAULT_SOURCE");c_sources(a,"Vendor/glfw/src/posix_time.c");c_sources(a,"Vendor/glfw/src/posix_module.c");c_sources(a,"Vendor/glfw/src/posix_thread.c");c_sources(a,"Vendor/glfw/src/x11_init.c");c_sources(a,"Vendor/glfw/src/x11_monitor.c");c_sources(a,"Vendor/glfw/src/x11_window.c");c_sources(a,"Vendor/glfw/src/xkb_unicode.c");c_sources(a,"Vendor/glfw/src/glx_context.c");c_sources(a,"Vendor/glfw/src/linux_joystick.c");c_sources(a,"Vendor/glfw/src/posix_poll.c");
#endif
}
void build(C_Build*b){C_Target*a=c_executable(b,"bge");c_sources(a,"main.c");c_sources(a,"Game/game.c");c_sources(a,"Game/game_update.c");c_sources(a,"Game/game_render.c");c_sources(a,"Game/player.c");c_sources(a,"Game/player_shot.c");c_sources(a,"Game/gun_core.c");c_sources(a,"Game/hud.c");c_sources(a,"Engine/Engine_lifecycle.c");c_sources(a,"Engine/Engine_resources.c");c_sources(a,"Engine/Engine_input.c");c_sources(a,"Engine/Engine_render.c");c_sources(a,"Engine/App.c");c_sources(a,"Engine/cam.c");c_sources(a,"Engine/gfx.c");c_sources(a,"Engine/text.c");c_sources(a,"Engine/level.c");c_sources(a,"Engine/level_store.c");c_sources(a,"Engine/portal.c");c_sources(a,"Engine/editor_model.c");c_sources(a,"Engine/editor_ui.c");c_sources(a,"Engine/editor_update.c");c_sources(a,"Engine/editor_visual.c");c_sources(a,"Engine/render.c");c_sources(a,"Engine/util/math.c");c_sources(a,"Engine/imgui_c.cpp");c_sources(a,"Vendor/glad/src/glad.c");add_imgui(a);add_glfw(a);c_include(a,".");c_include(a,"Engine");c_include(a,"Vendor/glad/include");c_include(a,"Vendor/glfw/include");c_include(a,"Vendor/glfw/src");c_include(a,"Vendor/imgui");c_define(a,"GL_SILENCE_DEPRECATION");c_flag(a,"-std=c++11");c_flag(a,"-Wall");c_flag(a,"-Wextra");
#ifdef _WIN32
c_link_system(a,"stdc++");c_link_system(a,"opengl32");c_link_system(a,"gdi32");c_link_system(a,"user32");c_link_system(a,"shell32");
#elif defined(__APPLE__)
c_link_system(a,"c++");c_framework(a,"OpenGL");c_framework(a,"Cocoa");c_framework(a,"IOKit");c_framework(a,"CoreFoundation");c_framework(a,"CoreVideo");c_framework(a,"QuartzCore");
#else
c_link_system(a,"stdc++");c_link_system(a,"GL");c_link_system(a,"m");c_link_system(a,"pthread");c_link_system(a,"dl");c_link_system(a,"rt");c_link_system(a,"X11");c_link_system(a,"Xrandr");c_link_system(a,"Xi");c_link_system(a,"Xinerama");c_link_system(a,"Xcursor");c_link_system(a,"Xext");
#endif
}
