#include "editor.h"
#include "imgui_c.h"
#include "state.h"
#include <stdint.h>
#include <math.h>
static editor_look_at_info_t pick(vec3s origin,vec3s direction){editor_look_at_info_t best={0};best.distance=100;for(i32 s=0;s<state.editor->level->sector_count;++s){level_sector_data_t*sector=&state.editor->level->sectors[s];for(i32 q=0;q<sector->quad_count;++q){f32 t=0;vec3s hit={0},local={0};if(level_ray_intersects_quad(origin,direction,&sector->quads[q],&t,&hit,&local)&&t<best.distance)best=(editor_look_at_info_t){true,sector->id,q,hit,local,t};}}return best;}
static bool cursor_ray(vec3s*origin,vec3s*direction){if(!state.win||!state.fb||state.fb->ww<=0||state.fb->wh<=0)return false;f64 x=0,y=0;glfwGetCursorPos(state.win,&x,&y);if(state.cursor_locked){x=(f64)state.fb->ww*.5;y=(f64)state.fb->wh*.5;}const f32 nx=(f32)(2*x/(f64)state.fb->ww-1),ny=(f32)(1-2*y/(f64)state.fb->wh),aspect=(f32)state.fb->ww/(f32)state.fb->wh,scale=tanf(DEG2RAD(45)*.5f);const vec3s right=vec3_normalize(vec3_cross(state.cam->front,state.cam->up)),up=vec3_normalize(vec3_cross(right,state.cam->front));*origin=state.cam->pos;*direction=vec3_normalize(vec3_add(state.cam->front,vec3_add(vec3_scale(right,nx*scale*aspect),vec3_scale(up,ny*scale))));return true;}
static vec3s on_plane(vec3s origin,vec3s direction,vec3s point,vec3s normal){const f32 d=vec3_dot(normal,direction);if(fabsf(d)<.0001f)return point;return vec3_add(origin,vec3_scale(direction,vec3_dot(vec3_sub(point,origin),normal)/d));}
static void pair_target(const editor_look_at_info_t*target){level_sector_data_t*source=editor_sector_by_id(state.editor->portal_link_sector_id),*dest=editor_sector_by_id(target->sector_id);const i32 si=state.editor->portal_link_wall_idx;if(!source||!dest||si<0||si>=source->quad_count||target->wall_id<0||target->wall_id>=dest->quad_count)return;if(source==dest&&si==target->wall_id)return;i32 id=1;while(id<INT32_MAX&&count_portal_quads(state.editor->level,id)>0)++id;if(id==INT32_MAX)return;source->quads[si].portal_id=id;dest->quads[target->wall_id].portal_id=id;}
void editor_update(void){if(!g_state||!state.editor||!state.editor->level||!state.cam)return;if(!editor_selected_quad())state.editor->template_quad.pos=(vec3s){roundf(state.cam->pos.x+state.cam->front.x*3),roundf(state.cam->pos.y+state.cam->front.y*3),roundf(state.cam->pos.z+state.cam->front.z*3)};vec3s origin,direction;if(!cursor_ray(&origin,&direction))return;const editor_look_at_info_t info=pick(origin,direction);const bool pressed=glfwGetMouseButton(state.win,GLFW_MOUSE_BUTTON_LEFT)==GLFW_PRESS,ctrl=glfwGetKey(state.win,GLFW_KEY_LEFT_CONTROL)==GLFW_PRESS||glfwGetKey(state.win,GLFW_KEY_RIGHT_CONTROL)==GLFW_PRESS,ui=!state.cursor_locked&&imgui_want_capture_mouse();if(pressed&&!state.editor->mouse_was_pressed&&!ui){if(state.editor->portal_link_mode){if(info.hit)pair_target(&info);state.editor->portal_link_mode=false;state.editor->portal_link_sector_id=-1;state.editor->portal_link_wall_idx=-1;}else if(info.hit){state.editor->selected_sector_id=info.sector_id;state.editor->selected_wall_idx=info.wall_id;level_quad_t*q=editor_selected_quad();if(q){state.editor->template_quad=*q;state.editor->template_mods=EDITOR_MOD_ALL;editor_open_wall_window(info.sector_id,info.wall_id);state.editor->drag_start_hit=info.hit_position;state.editor->drag_quad_start_pos=q->pos;state.editor->drag_quad_start_size=q->size;state.editor->drag_plane_normal=vec3_scale(state.cam->front,-1);const f32 top=q->size.y-info.local_hit.y,right=q->size.x-info.local_hit.x;state.editor->id=ctrl?(top<right&&top<5?EDITOR_RESIZE_TOP:(right<5?EDITOR_RESIZE_RIGHT:EDITOR_DRAG)):EDITOR_DRAG;}}else editor_clear_selection();}level_quad_t*q=editor_selected_quad();if(pressed&&q&&state.editor->id>=EDITOR_DRAG&&state.editor->id<=EDITOR_RESIZE_RIGHT){const vec3s hit=on_plane(origin,direction,state.editor->drag_start_hit,state.editor->drag_plane_normal),delta=vec3_sub(hit,state.editor->drag_start_hit);if(state.editor->id==EDITOR_DRAG){const vec3s p=vec3_add(state.editor->drag_quad_start_pos,delta);q->pos=(vec3s){roundf(p.x),roundf(p.y),roundf(p.z)};}else{const vec3s right=vec3_normalize(vec3_cross(state.cam->front,(vec3s){0,1,0})),up=vec3_normalize(vec3_cross(right,state.cam->front));if(state.editor->id==EDITOR_RESIZE_TOP)q->size.y=roundf(fmaxf(1,state.editor->drag_quad_start_size.y+vec3_dot(delta,up)));else q->size.x=roundf(fmaxf(1,state.editor->drag_quad_start_size.x+vec3_dot(delta,right)));}}if(!pressed&&state.editor->id!=EDITOR_PAINT)state.editor->id=EDITOR_IDLE;state.editor->mouse_was_pressed=pressed;}
