#include "editor.h"
#include "platform.h"
#include "imgui_c.h"
#include "state.h"
#include <stdio.h>
static const char* base(const char*p){if(!p)return"";const char*b=p;for(const char*x=p;*x;++x)if(*x=='/'||*x=='\\')b=x+1;return b;}
static i32 sector_index(i32 id){if(!state.editor||!state.editor->level)return-1;for(i32 i=0;i<state.editor->level->sector_count;++i)if(state.editor->level->sectors[i].id==id)return i;return-1;}
static level_quad_t* wall_quad(editor_wall_window_t*w,level_sector_data_t**os,i32*oi){if(!w||!state.editor||!state.editor->level)return NULL;const i32 si=sector_index(w->sector_id);if(si<0)return NULL;level_sector_data_t*s=&state.editor->level->sectors[si];if(w->quad_idx<0||w->quad_idx>=s->quad_count)return NULL;if(os)*os=s;if(oi)*oi=si;return&s->quads[w->quad_idx];}
static bool texture_picker(level_quad_t*q){bool changed=false;const char*cur=q->tex_id>=0&&q->tex_id<state.text->count?state.text->textures[q->tex_id].name:"none";char label[160];snprintf(label,sizeof(label),"%s [atlas]",base(cur));if(imgui_button(label))imgui_open_popup("texture_atlas");if(!imgui_begin_popup("texture_atlas"))return false;if(imgui_selectable("No Texture",q->tex_id<0)){q->tex_id=-1;changed=true;imgui_close_current_popup();}if(imgui_begin_child("texgrid",0,260,true)){i32 col=0;for(i32 i=0;i<state.text->count;++i){texture_t*t=&state.text->textures[i];if(col)imgui_same_line();f32 w=56,h=56;if(t->width>0&&t->height>0){const f32 a=(f32)t->width/(f32)t->height;if(a>1)h=w/a;else w=h*a;}imgui_push_id_int(i);const bool click=imgui_image_button("##tex",t->id,w,h);imgui_pop_id();if(click){q->tex_id=i;changed=true;imgui_close_current_popup();}if(imgui_is_item_hovered())imgui_set_tooltip("%s",base(t->name));col=(col+1)%4;}}imgui_end_child();imgui_end_popup();return changed;}
static void sync(level_quad_t*q){if(q){state.editor->template_quad=*q;state.editor->template_mods=EDITOR_MOD_ALL;}}
static void state_window(void){imgui_set_next_window_pos(0,0,IMGUI_COND_ALWAYS);imgui_set_next_window_bg_alpha(.85f);if(imgui_begin("STATE",NULL,IMGUI_WINDOW_ALWAYS_AUTO_RESIZE|IMGUI_WINDOW_NO_MOVE)){imgui_text("FPS: %.1f",app_get_fps());imgui_text("POS: %.2f %.2f %.2f",state.cam->pos.x,state.cam->pos.y,state.cam->pos.z);imgui_text("YAW: %.1f PITCH: %.1f",state.cam->yaw,state.cam->pitch);imgui_text("RES: %d x %d",state.fb->ww,state.fb->wh);imgui_text("LEVEL: %s",state.editor->level->name?state.editor->level->name:"Level");if(imgui_collapsing_header("Hotkeys")){imgui_text("Click+Drag Move | Ctrl+Drag Resize");imgui_text("N New | X Delete | R Reset | V Paint | Enter Deselect");imgui_text("7/8/9 Rotate | Shift reverse | E Mode | TAB Cursor");}}imgui_end();}
static bool wall_window(editor_wall_window_t*w){level_sector_data_t*s=NULL;i32 si=-1;level_quad_t*q=wall_quad(w,&s,&si);if(!q)return false;char title[48];snprintf(title,sizeof(title),"Wall##%u",w->id);bool open=true;imgui_set_next_window_bg_alpha(.9f);if(imgui_begin(title,&open,IMGUI_WINDOW_ALWAYS_AUTO_RESIZE)){imgui_text("Sector %d / Wall %d",q->sector_id,w->quad_idx);imgui_text("Pos %.0f %.0f %.0f",q->pos.x,q->pos.y,q->pos.z);imgui_text("Rot %.0f %.0f %.0f",q->rot.x,q->rot.y,q->rot.z);imgui_text("Size %.0f x %.0f | Portal %d",q->size.x,q->size.y,q->portal_id);const i32 count=state.editor->level->sector_count;const char*names[MAX_SECTORS_PER_LEVEL];char labels[MAX_SECTORS_PER_LEVEL][24];i32 current=si;for(i32 i=0;i<count;++i){snprintf(labels[i],sizeof(labels[i]),"Sector %d",state.editor->level->sectors[i].id);names[i]=labels[i];}if(count>0&&imgui_combo("Sector",&current,names,count)&&current!=si){level_sector_data_t*t=&state.editor->level->sectors[current];if(editor_move_quad_to_sector(s,t,w->quad_idx)){q=wall_quad(w,&s,&si);if(!q){imgui_end();return false;}}}const bool source=state.editor->portal_link_mode&&state.editor->portal_link_sector_id==s->id&&state.editor->portal_link_wall_idx==w->quad_idx;if(imgui_button(source?"Cancel portal link":"Select portal target")){state.editor->portal_link_mode=!source;state.editor->portal_link_sector_id=state.editor->portal_link_mode?s->id:-1;state.editor->portal_link_wall_idx=state.editor->portal_link_mode?w->quad_idx:-1;}if(q->portal_id>0&&imgui_button("Clear Portal")){q->portal_id=0;}if(imgui_checkbox("Flip Portal Side",&q->portal_side_flip))sync(q);if(imgui_color_edit3("Color",(f32*)&q->color))sync(q);if(texture_picker(q))sync(q);if(imgui_checkbox("Billboard",&q->is_billboard))sync(q);if(imgui_checkbox("Solid",&q->is_solid))sync(q);if(imgui_checkbox("Invisible",&q->is_invisible))sync(q);}imgui_end();return open;}
void editor_ui(void){if(!g_state||state.id!=STATE_EDITOR||!state.editor||!state.editor->level)return;state_window();for(i32 i=0;i<state.editor->ui_wall_window_count;){if(wall_window(&state.editor->ui_wall_windows[i]))++i;else state.editor->ui_wall_windows[i]=state.editor->ui_wall_windows[--state.editor->ui_wall_window_count];}}
