#include "editor.h"
#include "state.h"
#include <stdlib.h>
#include <string.h>
static bool ready(void){return g_state&&state.editor&&state.editor->level;}
level_sector_data_t* editor_sector_by_id(i32 id){if(!ready())return NULL;for(i32 i=0;i<state.editor->level->sector_count;++i)if(state.editor->level->sectors[i].id==id)return &state.editor->level->sectors[i];return NULL;}
level_sector_data_t* editor_selected_sector(void){return ready()&&state.editor->selected_sector_id>=0?editor_sector_by_id(state.editor->selected_sector_id):NULL;}
level_quad_t* editor_selected_quad(void){level_sector_data_t*s=editor_selected_sector();if(!s||state.editor->selected_wall_idx<0||state.editor->selected_wall_idx>=s->quad_count)return NULL;return &s->quads[state.editor->selected_wall_idx];}
void editor_clear_selection(void){if(!state.editor)return;state.editor->selected_sector_id=-1;state.editor->selected_wall_idx=-1;state.editor->template_quad=get_default_quad(state.cam);state.editor->template_mods=EDITOR_MOD_NONE;if(state.editor->id!=EDITOR_PAINT)state.editor->id=EDITOR_IDLE;}
void editor_init(void){if(!state.editor)return;level_data_t*l=state.editor->level;memset(state.editor,0,sizeof(*state.editor));state.editor->level=l;state.editor->selected_sector_id=-1;state.editor->selected_wall_idx=-1;state.editor->portal_link_sector_id=-1;state.editor->portal_link_wall_idx=-1;state.editor->next_wall_window_id=1;state.editor->template_quad=get_default_quad(state.cam);}
void editor_shutdown(void){if(!state.editor)return;level_data_t*l=state.editor->level;memset(state.editor,0,sizeof(*state.editor));state.editor->level=l;state.editor->selected_sector_id=-1;state.editor->selected_wall_idx=-1;state.editor->portal_link_sector_id=-1;state.editor->portal_link_wall_idx=-1;}
bool editor_add_sector(level_data_t*l){if(!l||l->sector_count<0||l->sector_count>=MAX_SECTORS_PER_LEVEL)return false;if(l->sector_capacity<=l->sector_count){i32 cap=l->sector_capacity>0?l->sector_capacity*2:16;if(cap<=l->sector_count)cap=l->sector_count+1;if(cap>MAX_SECTORS_PER_LEVEL)cap=MAX_SECTORS_PER_LEVEL;level_sector_data_t*p=realloc(l->sectors,sizeof(*p)*(size_t)cap);if(!p)return false;l->sectors=p;l->sector_capacity=cap;}i32 id=0;for(i32 i=0;i<l->sector_count;++i)if(l->sectors[i].id>=id)id=l->sectors[i].id+1;l->sectors[l->sector_count++]=(level_sector_data_t){.id=id,.light={1,1,1}};return true;}
bool editor_add_quad(level_sector_data_t*s,const level_quad_t*t){if(!ready()||!s||s->quad_count<0||s->quad_count>=MAX_QUADS_PER_SECTOR)return false;if(s->quad_capacity<=s->quad_count){i32 cap=s->quad_capacity>0?s->quad_capacity*2:16;if(cap<=s->quad_count)cap=s->quad_count+1;if(cap>MAX_QUADS_PER_SECTOR)cap=MAX_QUADS_PER_SECTOR;level_quad_t*p=realloc(s->quads,sizeof(*p)*(size_t)cap);if(!p)return false;s->quads=p;s->quad_capacity=cap;}level_quad_t q=t?*t:state.editor->template_quad;q.sector_id=s->id;const i32 idx=s->quad_count++;s->quads[idx]=q;state.editor->selected_sector_id=s->id;state.editor->selected_wall_idx=idx;editor_open_wall_window(s->id,idx);return true;}
bool editor_add_template_quad(void){if(!ready()||state.editor->level->sector_count<=0)return false;level_sector_data_t*s=editor_sector_by_id(state.editor->template_quad.sector_id);if(!s)s=&state.editor->level->sectors[0];return editor_add_quad(s,NULL);}
static void clear_pair(level_quad_t*q){if(!ready()||!q||q->portal_id<=0)return;const i32 id=q->portal_id;for(i32 s=0;s<state.editor->level->sector_count;++s){level_sector_data_t*sec=&state.editor->level->sectors[s];for(i32 i=0;i<sec->quad_count;++i)if(&sec->quads[i]!=q&&sec->quads[i].portal_id==id)sec->quads[i].portal_id=0;}q->portal_id=0;}
void editor_clear_portal_selected(void){clear_pair(editor_selected_quad());}
bool editor_delete_selected_quad(void){level_sector_data_t*s=editor_selected_sector();const i32 idx=state.editor?state.editor->selected_wall_idx:-1;if(!s||idx<0||idx>=s->quad_count)return false;clear_pair(&s->quads[idx]);memmove(&s->quads[idx],&s->quads[idx+1],sizeof(*s->quads)*(size_t)(s->quad_count-idx-1));--s->quad_count;for(i32 i=0;i<state.editor->ui_wall_window_count;){editor_wall_window_t*w=&state.editor->ui_wall_windows[i];if(w->sector_id!=s->id){++i;continue;}if(w->quad_idx==idx){*w=state.editor->ui_wall_windows[--state.editor->ui_wall_window_count];continue;}if(w->quad_idx>idx)--w->quad_idx;++i;}if(state.editor->portal_link_sector_id==s->id){if(state.editor->portal_link_wall_idx==idx){state.editor->portal_link_mode=false;state.editor->portal_link_sector_id=-1;state.editor->portal_link_wall_idx=-1;}else if(state.editor->portal_link_wall_idx>idx)--state.editor->portal_link_wall_idx;}editor_clear_selection();return true;}
bool editor_move_quad_to_sector(level_sector_data_t*from,level_sector_data_t*to,i32 idx){if(!ready()||!from||!to||from==to||idx<0||idx>=from->quad_count||to->quad_count>=MAX_QUADS_PER_SECTOR)return false;if(to->quad_capacity<=to->quad_count){i32 cap=to->quad_capacity>0?to->quad_capacity*2:16;if(cap>MAX_QUADS_PER_SECTOR)cap=MAX_QUADS_PER_SECTOR;level_quad_t*p=realloc(to->quads,sizeof(*p)*(size_t)cap);if(!p)return false;to->quads=p;to->quad_capacity=cap;}level_quad_t q=from->quads[idx];q.sector_id=to->id;const i32 ni=to->quad_count++;to->quads[ni]=q;memmove(&from->quads[idx],&from->quads[idx+1],sizeof(*from->quads)*(size_t)(from->quad_count-idx-1));--from->quad_count;for(i32 i=0;i<state.editor->ui_wall_window_count;++i){editor_wall_window_t*w=&state.editor->ui_wall_windows[i];if(w->sector_id!=from->id)continue;if(w->quad_idx==idx){w->sector_id=to->id;w->quad_idx=ni;}else if(w->quad_idx>idx)--w->quad_idx;}if(state.editor->selected_sector_id==from->id){if(state.editor->selected_wall_idx==idx){state.editor->selected_sector_id=to->id;state.editor->selected_wall_idx=ni;}else if(state.editor->selected_wall_idx>idx)--state.editor->selected_wall_idx;}if(state.editor->portal_link_sector_id==from->id){if(state.editor->portal_link_wall_idx==idx){state.editor->portal_link_sector_id=to->id;state.editor->portal_link_wall_idx=ni;}else if(state.editor->portal_link_wall_idx>idx)--state.editor->portal_link_wall_idx;}return true;}
void editor_reset_selected_quad(void){level_quad_t*q=editor_selected_quad();level_sector_data_t*s=editor_selected_sector();if(!q||!s)return;*q=get_default_quad(state.cam);q->sector_id=s->id;state.editor->template_quad=*q;state.editor->template_mods=EDITOR_MOD_ALL;}
void editor_toggle_paint_mode(void){if(state.editor)state.editor->id=state.editor->id==EDITOR_PAINT?EDITOR_IDLE:EDITOR_PAINT;}
void editor_rotate_selected_or_template(i32 axis,f32 d){if(!ready()||axis<0||axis>2)return;level_quad_t*sel=editor_selected_quad();level_quad_t*q=sel?sel:&state.editor->template_quad;f32*v=axis==0?&q->rot.x:axis==1?&q->rot.y:&q->rot.z;*v=fmodf(roundf(*v+d),360);if(*v<0)*v+=360;if(sel){state.editor->template_quad=*sel;state.editor->template_mods=EDITOR_MOD_ALL;}else state.editor->template_mods|=EDITOR_MOD_ROTATION;}
i32 count_portal_quads(const level_data_t*l,i32 id){if(!l||!l->sectors||id<=0)return 0;i32 n=0;for(i32 s=0;s<l->sector_count;++s)for(i32 q=0;q<l->sectors[s].quad_count;++q)if(l->sectors[s].quads[q].portal_id==id)++n;return n;}
void editor_open_wall_window(i32 sid,i32 idx){if(!state.editor||idx<0)return;for(i32 i=0;i<state.editor->ui_wall_window_count;++i){const editor_wall_window_t*w=&state.editor->ui_wall_windows[i];if(w->sector_id==sid&&w->quad_idx==idx)return;}if(state.editor->ui_wall_window_count>=MAX_WALL_WINDOWS)return;editor_wall_window_t*w=&state.editor->ui_wall_windows[state.editor->ui_wall_window_count++];*w=(editor_wall_window_t){state.editor->next_wall_window_id++,sid,idx};}
